import 'package:cricket_scorer/shared/widgets/neon_ball_orbit_loader.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:cricket_scorer/core/theme.dart';
import 'package:cricket_scorer/core/api_service.dart';
import 'package:cricket_scorer/core/app_config.dart';
import 'match_center_screen.dart';
import 'scoring_screen.dart';
import 'scorecard_screen.dart';

class LiveMatchesScreen extends StatefulWidget {
  const LiveMatchesScreen({super.key});

  @override
  State<LiveMatchesScreen> createState() => _LiveMatchesScreenState();
}

class _LiveMatchesScreenState extends State<LiveMatchesScreen> with SingleTickerProviderStateMixin {
  final ApiService _apiService = ApiService();
  late TabController _tabController;
  late AnimationController _pulseController;
  List<dynamic> _matches = [];
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(seconds: 1),
    )..repeat(reverse: true);
    _fetchMatches();
  }

  @override
  void dispose() {
    _tabController.dispose();
    _pulseController.dispose();
    super.dispose();
  }

  Future<void> _fetchMatches() async {
    setState(() => _isLoading = true);
    try {
      final res = await _apiService.getMatches();
      setState(() {
        // ONLY load matches generated by the Tournament workflow (tournament_id is not null)
        _matches = res.data.where((m) => m['tournament_id'] != null).toList();
        _isLoading = false;
      });
    } catch (e) {
      setState(() => _isLoading = false);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("Error fetching matches: $e"), backgroundColor: AppColors.error),
      );
    }
  }

  String _resolvePhotoUrl(String? path) {
    if (path == null || path.isEmpty) return "";
    if (path.startsWith("http")) return path;
    final uri = Uri.parse(AppConfig.baseUrl);
    final host = "${uri.scheme}://${uri.host}${uri.hasPort ? ':${uri.port}' : ''}";
    return "$host$path";
  }

  Widget _buildTeamLogo(String? logoUrl, String teamName, {double size = 28}) {
    if (logoUrl != null && logoUrl.isNotEmpty) {
      final url = _resolvePhotoUrl(logoUrl);
      return ClipRRect(
        borderRadius: BorderRadius.circular(size / 2),
        child: Image.network(
          url,
          width: size,
          height: size,
          fit: BoxFit.cover,
          errorBuilder: (context, error, stackTrace) => _buildTeamInitialsLogo(teamName, size),
        ),
      );
    } else {
      return _buildTeamInitialsLogo(teamName, size);
    }
  }

  Widget _buildTeamInitialsLogo(String name, double size) {
    final initials = name.trim().split(RegExp(r'\s+'))
        .take(2)
        .map((e) => e.isNotEmpty ? e[0].toUpperCase() : '')
        .join();
    return Container(
      width: size,
      height: size,
      decoration: BoxDecoration(
        color: AppColors.secondary.withOpacity(0.15),
        shape: BoxShape.circle,
      ),
      alignment: Alignment.center,
      child: Text(
        initials.isEmpty ? "?" : initials,
        style: GoogleFonts.outfit(
          fontWeight: FontWeight.bold,
          color: AppColors.secondary,
          fontSize: size * 0.4,
        ),
      ),
    );
  }

  Widget _buildEmptyState(String text) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.symmetric(horizontal: 40.0, vertical: 80.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.sports_cricket_outlined, size: 64, color: AppColors.textSecondary),
            const SizedBox(height: 16),
            Text(
              "No Matches Found",
              style: GoogleFonts.outfit(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.white),
            ),
            const SizedBox(height: 8),
            Text(
              text,
              textAlign: TextAlign.center,
              style: GoogleFonts.outfit(color: AppColors.textSecondary),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildLiveMatchCard(dynamic match) {
    final t1Name = match['team1_name'] ?? 'Team 1';
    final t2Name = match['team2_name'] ?? 'Team 2';
    final t1Logo = match['team1_logo_url'];
    final t2Logo = match['team2_logo_url'];
    
    final t1Runs = match['team1_runs'] ?? 0;
    final t1Wickets = match['team1_wickets'] ?? 0;
    final t1Overs = match['team1_overs'] ?? 0.0;
    final t2Runs = match['team2_runs'] ?? 0;
    final t2Wickets = match['team2_wickets'] ?? 0;
    final t2Overs = match['team2_overs'] ?? 0.0;
    
    final status = match['status'];
    final activeInnings = match['active_innings'] ?? 1;

    String scoreText1 = "$t1Runs/$t1Wickets ($t1Overs)";
    String scoreText2 = "$t2Runs/$t2Wickets ($t2Overs)";

    return InkWell(
      onTap: () async {
        if (status == 'toss' || status == 'team_selection' || status == 'ready') {
          await Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => MatchCenterScreen(matchId: match['id'])),
          );
        } else {
          await Navigator.push(
            context,
            MaterialPageRoute(builder: (context) => ScoringScreen(matchId: match['id'])),
          );
        }
        _fetchMatches();
      },
      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.all(16),
        decoration: AppColors.glassDecoration(borderRadius: BorderRadius.circular(16)),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  "Tournament: ${match['tournament_name'] ?? 'League'}",
                  style: GoogleFonts.outfit(color: AppColors.primary, fontSize: 11, fontWeight: FontWeight.bold),
                ),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(
                    color: (status == 'ready' ? Colors.amber : (status == 'toss' || status == 'team_selection' ? Colors.orange : Colors.red)).withOpacity(0.12),
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: Row(
                    children: [
                      if (status != 'ready' && status != 'toss' && status != 'team_selection') ...[
                        AnimatedBuilder(
                          animation: _pulseController,
                          builder: (context, child) {
                            return Opacity(
                              opacity: _pulseController.value,
                              child: Container(
                                width: 6,
                                height: 6,
                                decoration: const BoxDecoration(
                                  shape: BoxShape.circle,
                                  color: Colors.red,
                                ),
                              ),
                            );
                          },
                        ),
                        const SizedBox(width: 5),
                      ],
                      Text(
                        status == 'ready' ? 'READY' : (status == 'toss' || status == 'team_selection' ? 'PRE-MATCH' : 'LIVE'),
                        style: GoogleFonts.outfit(
                          color: status == 'ready' ? Colors.amber : (status == 'toss' || status == 'team_selection' ? Colors.orange : Colors.red),
                          fontSize: 10,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                _buildTeamLogo(t1Logo, t1Name),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    t1Name,
                    style: GoogleFonts.outfit(fontWeight: FontWeight.w600, color: Colors.white),
                  ),
                ),
                Text(
                  scoreText1,
                  style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: activeInnings == 1 ? AppColors.primary : Colors.white70),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                _buildTeamLogo(t2Logo, t2Name),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    t2Name,
                    style: GoogleFonts.outfit(fontWeight: FontWeight.w600, color: Colors.white),
                  ),
                ),
                Text(
                  scoreText2,
                  style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: activeInnings == 2 ? AppColors.primary : Colors.white70),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Text(
              "Venue: ${match['venue'] ?? 'Stadium'}",
              style: GoogleFonts.outfit(fontSize: 12, color: AppColors.textSecondary),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildUpcomingMatchCard(dynamic match) {
    final t1Name = match['team1_name'] ?? 'Team 1';
    final t2Name = match['team2_name'] ?? 'Team 2';
    final t1Logo = match['team1_logo_url'];
    final t2Logo = match['team2_logo_url'];

    return InkWell(
      onTap: () async {
        await Navigator.push(
          context,
          MaterialPageRoute(builder: (context) => MatchCenterScreen(matchId: match['id'])),
        );
        _fetchMatches();
      },
      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.all(16),
        decoration: AppColors.glassDecoration(borderRadius: BorderRadius.circular(16)),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  "Tournament: ${match['tournament_name'] ?? 'League'}",
                  style: GoogleFonts.outfit(color: AppColors.secondary, fontSize: 11, fontWeight: FontWeight.bold),
                ),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(
                    color: AppColors.primary.withOpacity(0.12),
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: Text(
                    "UPCOMING",
                    style: GoogleFonts.outfit(color: AppColors.primary, fontSize: 10, fontWeight: FontWeight.bold),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                _buildTeamLogo(t1Logo, t1Name),
                const SizedBox(width: 8),
                Text(
                  t1Name,
                  style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white),
                ),
                const Spacer(),
                Text(
                  "vs",
                  style: GoogleFonts.outfit(color: AppColors.textSecondary, fontStyle: FontStyle.italic),
                ),
                const Spacer(),
                Text(
                  t2Name,
                  style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white),
                ),
                const SizedBox(width: 8),
                _buildTeamLogo(t2Logo, t2Name),
              ],
            ),
            const SizedBox(height: 12),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  "Venue: ${match['venue'] ?? 'Stadium'}",
                  style: GoogleFonts.outfit(fontSize: 12, color: AppColors.textSecondary),
                ),
                Text(
                  "Overs: ${match['over_limit']}",
                  style: GoogleFonts.outfit(fontSize: 12, color: AppColors.textSecondary, fontWeight: FontWeight.bold),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCompletedMatchCard(dynamic match) {
    final t1Name = match['team1_name'] ?? 'Team 1';
    final t2Name = match['team2_name'] ?? 'Team 2';
    final t1Logo = match['team1_logo_url'];
    final t2Logo = match['team2_logo_url'];
    
    final t1Runs = match['team1_runs'] ?? 0;
    final t1Wickets = match['team1_wickets'] ?? 0;
    final t1Overs = match['team1_overs'] ?? 0.0;
    final t2Runs = match['team2_runs'] ?? 0;
    final t2Wickets = match['team2_wickets'] ?? 0;
    final t2Overs = match['team2_overs'] ?? 0.0;

    String resultText = match['win_margin_text'] ?? "Match Completed";

    return InkWell(
      onTap: () async {
        await Navigator.push(
          context,
          MaterialPageRoute(builder: (context) => ScorecardScreen(matchId: match['id'])),
        );
      },
      child: Container(
        margin: const EdgeInsets.only(bottom: 12),
        padding: const EdgeInsets.all(16),
        decoration: AppColors.glassDecoration(borderRadius: BorderRadius.circular(16)),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  "Tournament: ${match['tournament_name'] ?? 'League'}",
                  style: GoogleFonts.outfit(color: AppColors.textSecondary, fontSize: 11, fontWeight: FontWeight.bold),
                ),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(
                    color: (match['status'] == 'abandoned' ? Colors.grey : (match['status'] == 'no_result' ? Colors.redAccent : Colors.blueAccent)).withOpacity(0.12),
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: Text(
                    (match['status']?.toString().toUpperCase() ?? 'COMPLETED'),
                    style: GoogleFonts.outfit(
                      color: match['status'] == 'abandoned' ? Colors.grey : (match['status'] == 'no_result' ? Colors.redAccent : Colors.blueAccent),
                      fontSize: 10,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Row(
              children: [
                _buildTeamLogo(t1Logo, t1Name),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    t1Name,
                    style: GoogleFonts.outfit(fontWeight: FontWeight.w600, color: Colors.white),
                  ),
                ),
                Text(
                  "$t1Runs/$t1Wickets ($t1Overs)",
                  style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white),
                ),
              ],
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                _buildTeamLogo(t2Logo, t2Name),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    t2Name,
                    style: GoogleFonts.outfit(fontWeight: FontWeight.w600, color: Colors.white),
                  ),
                ),
                Text(
                  "$t2Runs/$t2Wickets ($t2Overs)",
                  style: GoogleFonts.outfit(fontWeight: FontWeight.bold, color: Colors.white),
                ),
              ],
            ),
            const Divider(color: Colors.white10, height: 20),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Expanded(
                  child: Text(
                    resultText,
                    style: GoogleFonts.outfit(fontSize: 12, color: AppColors.primary, fontWeight: FontWeight.bold),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
                const Icon(Icons.arrow_forward_ios_rounded, color: AppColors.textSecondary, size: 12),
              ],
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    // Categorize tournament matches
    final liveMatches = _matches.where((m) {
      final status = m['status'];
      return status == 'innings1' || status == 'innings2' || status == 'team_selection' || 
             status == 'toss' || status == 'ready' || status == 'live' || status == 'innings_break';
    }).toList();

    final upcomingMatches = _matches.where((m) => m['status'] == 'scheduled').toList();
    final completedMatches = _matches.where((m) => m['status'] == 'completed' || m['status'] == 'abandoned' || m['status'] == 'no_result').toList();

    return Scaffold(
      appBar: AppBar(
        title: const Text("Tournament Matches"),
        bottom: TabBar(
          controller: _tabController,
          indicatorColor: AppColors.primary,
          labelColor: AppColors.primary,
          unselectedLabelColor: Colors.white60,
          tabs: const [
            Tab(text: "LIVE"),
            Tab(text: "UPCOMING"),
            Tab(text: "COMPLETED"),
          ],
        ),
      ),
      body: RefreshIndicator(
        onRefresh: _fetchMatches,
        color: AppColors.primary,
        backgroundColor: AppColors.surface,
        child: _isLoading
            ? const Center(child: NeonBallOrbitLoader())
            : TabBarView(
                controller: _tabController,
                children: [
                  // Tab 1: Live Matches
                  liveMatches.isEmpty
                      ? _buildEmptyState("No live matches are currently in progress. Start one from the scheduled fixtures!")
                      : ListView.builder(
                          padding: const EdgeInsets.all(16.0),
                          itemCount: liveMatches.length,
                          itemBuilder: (context, index) => _buildLiveMatchCard(liveMatches[index]),
                        ),
                  
                  // Tab 2: Upcoming Matches
                  upcomingMatches.isEmpty
                      ? _buildEmptyState("No upcoming matches scheduled. Organizer needs to generate and publish fixtures!")
                      : ListView.builder(
                          padding: const EdgeInsets.all(16.0),
                          itemCount: upcomingMatches.length,
                          itemBuilder: (context, index) => _buildUpcomingMatchCard(upcomingMatches[index]),
                        ),

                  // Tab 3: Completed Matches
                  completedMatches.isEmpty
                      ? _buildEmptyState("No completed matches found in this tournament.")
                      : ListView.builder(
                          padding: const EdgeInsets.all(16.0),
                          itemCount: completedMatches.length,
                          itemBuilder: (context, index) => _buildCompletedMatchCard(completedMatches[index]),
                        ),
                ],
              ),
      ),
    );
  }
}