"""add_officials_to_match

Revision ID: 49ccc345b8c4
Revises: b8db25128010
Create Date: 2026-06-30 21:43:11.549863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ccc345b8c4'
down_revision: Union[str, None] = 'b8db25128010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('umpire_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('scorer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_column('scorer_name')
        batch_op.drop_column('umpire_name')
    # ### end Alembic commands ###
