"""initial_schema

Revision ID: b2017fb6364a
Revises: 
Create Date: 2026-06-14 19:41:22.457486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2017fb6364a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.Column('last_otp_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('batting_style', sa.String(), nullable=False),
    sa.Column('bowling_style', sa.String(), nullable=False),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('career_runs', sa.Integer(), nullable=True),
    sa.Column('career_wickets', sa.Integer(), nullable=True),
    sa.Column('matches_played', sa.Integer(), nullable=True),
    sa.Column('batting_average', sa.Float(), nullable=True),
    sa.Column('strike_rate', sa.Float(), nullable=True),
    sa.Column('economy', sa.Float(), nullable=True),
    sa.Column('highest_score', sa.Integer(), nullable=True),
    sa.Column('best_bowling_figures', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token'), ['token'], unique=True)

    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('captain_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['captain_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=True)

    op.create_table('team_players',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'player_id'),
    sa.UniqueConstraint('player_id')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('num_teams', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tournament_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('team1_id', sa.UUID(), nullable=False),
    sa.Column('team2_id', sa.UUID(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('over_limit', sa.Integer(), nullable=False),
    sa.Column('toss_winner_id', sa.UUID(), nullable=True),
    sa.Column('toss_decision', sa.String(), nullable=True),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('win_margin_runs', sa.Integer(), nullable=True),
    sa.Column('win_margin_wickets', sa.Integer(), nullable=True),
    sa.Column('tournament_stage', sa.String(), nullable=True),
    sa.Column('bracket_code', sa.String(), nullable=True),
    sa.Column('current_striker_id', sa.UUID(), nullable=True),
    sa.Column('current_non_striker_id', sa.UUID(), nullable=True),
    sa.Column('current_bowler_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_bowler_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_non_striker_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_striker_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['toss_winner_id'], ['teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament_teams',
    sa.Column('tournament_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tournament_id', 'team_id')
    )
    op.create_table('innings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('innings_number', sa.Integer(), nullable=False),
    sa.Column('batting_team_id', sa.UUID(), nullable=False),
    sa.Column('bowling_team_id', sa.UUID(), nullable=False),
    sa.Column('total_runs', sa.Integer(), nullable=True),
    sa.Column('total_wickets', sa.Integer(), nullable=True),
    sa.Column('total_overs', sa.Float(), nullable=True),
    sa.Column('extras_byes', sa.Integer(), nullable=True),
    sa.Column('extras_legbyes', sa.Integer(), nullable=True),
    sa.Column('extras_wides', sa.Integer(), nullable=True),
    sa.Column('extras_noballs', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['batting_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bowling_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_squads',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('is_playing_xi', sa.Boolean(), nullable=True),
    sa.Column('is_captain', sa.Boolean(), nullable=True),
    sa.Column('is_wicketkeeper', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', 'team_id', 'player_id')
    )
    op.create_table('balls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('innings_id', sa.UUID(), nullable=False),
    sa.Column('over_number', sa.Integer(), nullable=False),
    sa.Column('ball_number', sa.Integer(), nullable=False),
    sa.Column('bowler_id', sa.UUID(), nullable=False),
    sa.Column('batsman_id', sa.UUID(), nullable=False),
    sa.Column('non_striker_id', sa.UUID(), nullable=False),
    sa.Column('runs_batsman', sa.Integer(), nullable=True),
    sa.Column('runs_extras', sa.Integer(), nullable=True),
    sa.Column('extra_type', sa.String(), nullable=True),
    sa.Column('is_wicket', sa.Boolean(), nullable=True),
    sa.Column('wicket_type', sa.String(), nullable=True),
    sa.Column('player_dismissed_id', sa.UUID(), nullable=True),
    sa.Column('fielder_id', sa.UUID(), nullable=True),
    sa.Column('commentary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batsman_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fielder_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['non_striker_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_dismissed_id'], ['players.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balls')
    op.drop_table('match_squads')
    op.drop_table('innings')
    op.drop_table('tournament_teams')
    op.drop_table('matches')
    op.drop_table('tournaments')
    op.drop_table('team_players')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))

    op.drop_table('teams')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token'))

    op.drop_table('refresh_tokens')
    op.drop_table('players')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
